// ============================================================
// FITTRACK — RECIPES.JS
// 150 curated protein-rich vegetarian recipes (no soy, no egg)
// Indian YouTube channels: Ranveer Brar · Sanjyot Keer · Kunal Kapur
//   Venkatesh Bhat · Vahchef · Sanjeev Kapoor · Hebbar's Kitchen
//   Nisha Madhulika · Chef Harpal · Kabita's Kitchen · Rajshri Food
// Categories: Beverages · Paneer · Curd & Cheese · Dal & Lentils
//   Legumes & Beans · Sprouts · South Indian · Millets & Grains
//   Greens & Sabzi · Nuts & Seeds · Snacks & Street Food · Rice Dishes
// ============================================================

var RECIPE_CATS = [
  { id:'all',        label:'All',             emoji:'🍽️' },
  { id:'beverage',   label:'Beverages',        emoji:'🥤' },
  { id:'paneer',     label:'Paneer',           emoji:'🧀' },
  { id:'cheese',     label:'Curd & Cheese',    emoji:'🥛' },
  { id:'dal',        label:'Dal & Lentils',    emoji:'🥣' },
  { id:'legumes',    label:'Legumes & Beans',  emoji:'🫘' },
  { id:'sprouts',    label:'Sprouts',          emoji:'🌱' },
  { id:'southindian',label:'South Indian',     emoji:'🫓' },
  { id:'millet',     label:'Millets & Grains', emoji:'🌾' },
  { id:'greens',     label:'Greens & Sabzi',   emoji:'🥬' },
  { id:'nuts',       label:'Nuts & Seeds',     emoji:'🥜' },
  { id:'snacks',     label:'Snacks & Street',  emoji:'🍢' },
  { id:'rice',       label:'Rice Dishes',      emoji:'🍚' },
];

// bestMeal: array of 'breakfast' | 'lunch' | 'snacks' | 'dinner'
// difficulty: 'easy' | 'medium' | 'hard'
// prepTime: minutes

var RECIPES = [

  // ── BEVERAGES ─────────────────────────────────────────── (12) ──
  { id:3001, name:'Sattu Sharbat',        cat:'beverage', emoji:'🥤', protein:20, cal:220, carbs:32, fat:4,  fiber:3, sodium:180, calcium:45,  iron:3.0, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:5,  ytId:'tK9D_Z_RP0s', desc:"Bihar's ancient 20g protein drink — roasted gram flour in cold water with lemon, black salt and mint, zero cooking required" },
  { id:3002, name:'Thandai',              cat:'beverage', emoji:'🥤', protein:9,  cal:290, carbs:28, fat:16, fiber:3, sodium:120, calcium:250, iron:1.5, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:20, ytId:'NcO_HZuFI5c', desc:'Mughlai cold milk blended with almonds, melon seeds, rose petals, fennel and cardamom — the real Holi drink, high calcium' },
  { id:3003, name:'Badam Doodh',          cat:'beverage', emoji:'🥤', protein:9,  cal:240, carbs:18, fat:14, fiber:2, sodium:90,  calcium:280, iron:1.2, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:10, ytId:'upbxk0Uwuus', desc:'Hot or cold saffron almond milk — Mughlai classic that is genuinely calming, sleep-promoting and protein-dense' },
  { id:3004, name:'Anjeer Doodh',         cat:'beverage', emoji:'🥤', protein:8,  cal:250, carbs:32, fat:8,  fiber:4, sodium:80,  calcium:240, iron:2.5, vitC:3,  servingSize:'300ml',       bestMeal:['breakfast'],                difficulty:'easy',   prepTime:10, ytId:null,          desc:'Dried figs soaked overnight and blended with warm milk — iron, calcium and natural sugar in one unassuming glass' },
  { id:3005, name:'Kesar Pista Lassi',    cat:'beverage', emoji:'🥤', protein:10, cal:240, carbs:24, fat:10, fiber:2, sodium:90,  calcium:240, iron:1.0, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:10, ytId:null,          desc:'Thick Punjabi lassi with crushed pistachios and saffron — completely different character from plain or sweet lassi' },
  { id:3006, name:'Ragi Malt',            cat:'beverage', emoji:'🥤', protein:7,  cal:180, carbs:32, fat:3,  fiber:4, sodium:60,  calcium:290, iron:3.5, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast'],                difficulty:'easy',   prepTime:15, ytId:'d1_9STTBcfQ',  desc:'Finger millet roasted and cooked into a porridge-drink with jaggery and coconut — highest dietary calcium of any grain' },
  { id:3007, name:'Peanut Lassi',         cat:'beverage', emoji:'🥤', protein:13, cal:290, carbs:20, fat:16, fiber:2, sodium:120, calcium:200, iron:1.2, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:5,  ytId:null,          desc:'Peanut butter blended into thick curd with honey — the desi gym drink nobody talks about, genuinely filling at 13g protein' },
  { id:3008, name:'Masala Chaas',         cat:'beverage', emoji:'🥤', protein:5,  cal:100, carbs:8,  fat:3,  fiber:1, sodium:380, calcium:180, iron:0.5, vitC:4,  servingSize:'300ml',       bestMeal:['lunch','snacks'],           difficulty:'easy',   prepTime:5,  ytId:'2h68dKqskT0',  desc:'Rajasthani spiced chaas with roasted cumin, ginger and curry leaves — best digestive drink in India, not the plain version' },
  { id:3009, name:'Sattu Lassi',          cat:'beverage', emoji:'🥤', protein:18, cal:260, carbs:28, fat:6,  fiber:3, sodium:200, calcium:210, iron:2.8, vitC:2,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:5,  ytId:null,          desc:'Sattu mixed into thick lassi — Bihar\'s answer to protein smoothies, tangy and filling, requires no blender just a churner' },
  { id:3010, name:'Kokum Solkadhi',       cat:'beverage', emoji:'🥤', protein:3,  cal:120, carbs:8,  fat:8,  fiber:1, sodium:260, calcium:40,  iron:0.8, vitC:5,  servingSize:'200ml',       bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:10, ytId:null,          desc:'Goan pink digestive drink with coconut milk and kokum — cooling, probiotic and drunk after Konkan meals' },
  { id:3011, name:'Rose Falooda',         cat:'beverage', emoji:'🥤', protein:8,  cal:290, carbs:44, fat:8,  fiber:3, sodium:100, calcium:240, iron:1.5, vitC:3,  servingSize:'350ml',       bestMeal:['snacks'],                   difficulty:'easy',   prepTime:15, ytId:'IDoNeoUGqic',  desc:'Layered Mumbai falooda with rose syrup, sabja seeds, basundi and vermicelli — iconic street dessert-drink unlike any smoothie' },
  { id:3012, name:'Haldi Doodh',          cat:'beverage', emoji:'🥤', protein:8,  cal:200, carbs:16, fat:10, fiber:1, sodium:80,  calcium:290, iron:1.0, vitC:2,  servingSize:'300ml',       bestMeal:['snacks','dinner'],          difficulty:'easy',   prepTime:10, ytId:'L_F8VeK8VPQ',  desc:'Warm milk with turmeric, black pepper, ashwagandha and ghee — the anti-inflammatory bedtime drink that actually works' },

  // ── PANEER ─────────────────────────────────────────────── (15) ──
  { id:2110, name:'Paneer Angara',          cat:'paneer', emoji:'🧀', protein:20, cal:310, carbs:8,  fat:22, fiber:2, sodium:560, calcium:260, iron:2.0, vitC:8,  servingSize:'1 bowl',      bestMeal:['dinner'],                  difficulty:'medium', prepTime:30, ytId:'2llKoPqi0Bc', desc:'Coal-smoked paneer in spiced onion-tomato gravy — dhungar technique gives it a flame-kissed depth impossible to get from a pan' },
  { id:2111, name:'Paneer Kali Mirch',      cat:'paneer', emoji:'🧀', protein:19, cal:295, carbs:7,  fat:21, fiber:1, sodium:520, calcium:250, iron:1.8, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'08NwR-LTz2c', desc:'Mughlai white cashew-cream gravy loaded with cracked black pepper — rarely made at home, zero tomato, completely different' },
  { id:2112, name:'Paneer Lababdar',        cat:'paneer', emoji:'🧀', protein:17, cal:330, carbs:12, fat:24, fiber:2, sodium:540, calcium:250, iron:1.8, vitC:10, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:35, ytId:'1DbrPChGnpk', desc:'Punjab dhaba icon — rich slow-cooked tomato-cashew gravy more nuanced than butter paneer, the dal makhani of paneer dishes' },
  { id:2113, name:'Paneer Do Pyaza',        cat:'paneer', emoji:'🧀', protein:18, cal:280, carbs:10, fat:20, fiber:3, sodium:510, calcium:240, iron:1.9, vitC:12, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'jwk6G_-FZKM', desc:'Double-onion technique — onions in the base AND as textured chunks — intensely savoury dhaba style unlike any standard paneer' },
  { id:2114, name:'Paneer Pasanda',         cat:'paneer', emoji:'🧀', protein:18, cal:360, carbs:10, fat:28, fiber:2, sodium:500, calcium:270, iron:2.0, vitC:5,  servingSize:'1 bowl',      bestMeal:['dinner'],                  difficulty:'hard',   prepTime:45, ytId:'Tjpnv6U9CrY', desc:'Slit paneer stuffed with dry fruit, shallow-fried then simmered in Mughlai almond-cream gravy — wedding food made at home' },
  { id:2115, name:'Paneer Khurchan',        cat:'paneer', emoji:'🧀', protein:17, cal:270, carbs:7,  fat:19, fiber:2, sodium:510, calcium:240, iron:1.7, vitC:15, servingSize:'1 plate',     bestMeal:['breakfast','dinner'],       difficulty:'easy',   prepTime:20, ytId:'04UaScefYNQ', desc:'Tawa-scraped paneer with peppers and spices — roadside dhaba dry technique completely different from bhurji' },
  { id:2116, name:'Achari Paneer Tikka',    cat:'paneer', emoji:'🧀', protein:22, cal:290, carbs:6,  fat:20, fiber:2, sodium:580, calcium:255, iron:1.8, vitC:6,  servingSize:'6 pieces',    bestMeal:['snacks','dinner'],          difficulty:'medium', prepTime:35, ytId:'TFsaZ3M7-HM', desc:'Paneer marinated in kalonji, fennel and mustard pickle spices — smoky, tangy and rarely on restaurant menus outside Delhi' },
  { id:2117, name:'Paneer Hariyali Kebab',  cat:'paneer', emoji:'🧀', protein:21, cal:260, carbs:5,  fat:18, fiber:2, sodium:500, calcium:250, iron:2.0, vitC:18, servingSize:'6 pieces',    bestMeal:['snacks','dinner'],          difficulty:'medium', prepTime:30, ytId:'jd5KVvkJm3o', desc:'Skewers marinated in spinach-mint-coriander paste — vibrant green, aromatic restaurant starter few people make at home' },
  { id:2118, name:'Methi Malai Paneer',     cat:'paneer', emoji:'🧀', protein:16, cal:300, carbs:10, fat:22, fiber:3, sodium:480, calcium:240, iron:3.0, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'KKXaVuRl6pk', desc:'Fenugreek-forward creamy sauce, mildly bitter and rich — restaurant classic almost never made at home' },
  { id:2119, name:'Paneer Malai Kofta',     cat:'paneer', emoji:'🧀', protein:15, cal:400, carbs:16, fat:30, fiber:2, sodium:520, calcium:240, iron:1.8, vitC:6,  servingSize:'4 koftas',    bestMeal:['dinner'],                  difficulty:'hard',   prepTime:50, ytId:'oB86C26Lw1E', desc:'Paneer-potato balls stuffed with nuts, fried crisp, simmered in saffron-cream tomato gravy — the definitive dinner party dish' },
  { id:2120, name:'Dahi Paneer Tikka',      cat:'paneer', emoji:'🧀', protein:22, cal:280, carbs:6,  fat:18, fiber:1, sodium:520, calcium:280, iron:1.6, vitC:5,  servingSize:'6 pieces',    bestMeal:['snacks','dinner'],          difficulty:'medium', prepTime:40, ytId:'oUGUv3Na3WY', desc:'Thick curd-marinated paneer with kasuri methi — softer and smokier than red-marinade tikka, the tandoor restaurant favourite' },
  { id:2121, name:'Paneer Lasooni Saag',    cat:'paneer', emoji:'🧀', protein:17, cal:260, carbs:9,  fat:18, fiber:4, sodium:500, calcium:260, iron:4.0, vitC:20, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'Ki9CAhr2s_s', desc:'Paneer in deeply garlicked saag — 3x more garlic than palak paneer, minus the cream, the authentic dhaba version' },
  { id:3013, name:'Paneer Ghee Roast',      cat:'paneer', emoji:'🧀', protein:20, cal:350, carbs:8,  fat:27, fiber:2, sodium:580, calcium:260, iron:2.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['dinner'],                  difficulty:'hard',   prepTime:40, ytId:'kscC5MVhB1E', desc:'Mangalorean dry-roasted paneer in fiery Bydagi chilli-tamarind masala — one of the boldest paneer dishes in Indian cooking' },
  { id:3014, name:'Paneer 65',              cat:'paneer', emoji:'🧀', protein:22, cal:320, carbs:12, fat:22, fiber:2, sodium:600, calcium:260, iron:2.2, vitC:6,  servingSize:'6 pieces',    bestMeal:['snacks','dinner'],          difficulty:'medium', prepTime:30, ytId:'Rs49YKc8iJw', desc:'Crispy fried paneer tossed in Bangalorean spicy sauce — South Indian restaurant starter unlike any North Indian paneer' },
  { id:3015, name:'Paneer Chettinad',       cat:'paneer', emoji:'🧀', protein:19, cal:320, carbs:9,  fat:24, fiber:2, sodium:540, calcium:250, iron:2.5, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:40, ytId:'WeULwx3ZCUM', desc:'Paneer in Chettinad masala with kalpasi, marathi mokku and stone flower — spice complexity impossible to achieve with less than 12 spices' },

  // ── CURD & CHEESE ─────────────────────────────────────── (10) ──
  { id:2062, name:'Shrikhand',             cat:'cheese', emoji:'🥛', protein:10, cal:220, carbs:28, fat:6,  fiber:1, sodium:80,  calcium:200, iron:0.5, vitC:3,  servingSize:'150g',        bestMeal:['snacks'],                  difficulty:'easy',   prepTime:10, ytId:null,          desc:'Strained yogurt sweetened with saffron and cardamom — Gujarati-Maharashtrian dessert with real protein, zero gelatin or additives' },
  { id:2063, name:'Kesar Badam Lassi',     cat:'cheese', emoji:'🥛', protein:10, cal:200, carbs:22, fat:5,  fiber:1, sodium:80,  calcium:220, iron:0.4, vitC:5,  servingSize:'300ml',       bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:5,  ytId:null,          desc:'Full-fat curd blended with almond paste and saffron — desi protein drink with 10g protein and no powder required' },
  { id:2133, name:'Dahi Ke Kebab',         cat:'cheese', emoji:'🥛', protein:10, cal:180, carbs:12, fat:10, fiber:2, sodium:320, calcium:180, iron:0.8, vitC:5,  servingSize:'4 kebabs',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:30, ytId:'_cOTZrxINTA', desc:"Melt-in-mouth patties from hung curd and paneer — MasterChef India's iconic vegetarian starter, extraordinary when made right" },
  { id:2134, name:'Kadhi Pakoda',          cat:'cheese', emoji:'🥛', protein:10, cal:250, carbs:28, fat:10, fiber:3, sodium:440, calcium:160, iron:1.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:40, ytId:'zucwY4pw2Rk', desc:'Punjabi besan-yogurt gravy with golden fried pakodas — slow-simmered 40 minutes, leagues above the 10-minute version' },
  { id:2135, name:"Labneh with Za'atar",   cat:'cheese', emoji:'🥛', protein:8,  cal:160, carbs:5,  fat:11, fiber:1, sodium:220, calcium:200, iron:1.0, vitC:4,  servingSize:'100g',        bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:10, ytId:null,          desc:"Middle Eastern strained yogurt with za'atar herbs and pumpkin seeds — high-protein breakfast dip taking over Indian cafes" },
  { id:3016, name:'Mor Kuzhambu',          cat:'cheese', emoji:'🥛', protein:5,  cal:160, carbs:12, fat:10, fiber:2, sodium:340, calcium:160, iron:0.8, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:20, ytId:'7grvldzz0WE', desc:'Kerala thin yogurt curry with coconut, cumin and turmeric — much lighter than Punjabi kadhi, drunk alongside rice' },
  { id:3017, name:'Chena Poda',            cat:'cheese', emoji:'🥛', protein:14, cal:260, carbs:24, fat:12, fiber:1, sodium:180, calcium:240, iron:1.0, vitC:2,  servingSize:'2 slices',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:50, ytId:null,          desc:"Odisha's caramelised baked cottage cheese — only Indian dessert that is baked, with a dark golden top and soft cheesy centre" },
  { id:3018, name:'Kalmi Vada',            cat:'cheese', emoji:'🥛', protein:11, cal:220, carbs:24, fat:8,  fiber:5, sodium:360, calcium:60,  iron:3.0, vitC:4,  servingSize:'4 pieces',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:25, ytId:null,          desc:'Hyderabadi chana dal fritters served with curd — Ramadan special eaten year-round in Hyderabad, unknown outside it' },
  { id:3019, name:'Chaas Kadhi',           cat:'cheese', emoji:'🥛', protein:6,  cal:140, carbs:14, fat:5,  fiber:1, sodium:440, calcium:160, iron:0.8, vitC:4,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:'qxF1gGNeF8I', desc:'Rajasthani thin buttermilk kadhi — the besan barely thickens it, a completely different dish from Punjabi kadhi' },
  { id:3020, name:'Mishti Doi',            cat:'cheese', emoji:'🥛', protein:8,  cal:190, carbs:28, fat:4,  fiber:0, sodium:60,  calcium:220, iron:0.5, vitC:2,  servingSize:'150g',        bestMeal:['snacks'],                  difficulty:'easy',   prepTime:15, ytId:'WJVkaeGvj28', desc:'Bengali slow-baked sweetened yogurt with palm jaggery — natural caramel flavour unlike any yogurt you have had' },

  // ── DAL & LENTILS ─────────────────────────────────────── (15) ──
  { id:2035, name:'Masoor Dal Soup',       cat:'dal',    emoji:'🥣', protein:10, cal:180, carbs:26, fat:3,  fiber:7, sodium:380, calcium:50,  iron:3.5, vitC:6,  servingSize:'1 bowl',      bestMeal:['snacks','lunch','dinner'],  difficulty:'easy',   prepTime:20, ytId:'xeYe7NrYeiM', desc:'Red lentil soup with roasted cumin, turmeric and lemon — light but protein-dense, quick and immune-boosting' },
  { id:2041, name:'Chana Dal Coconut',     cat:'dal',    emoji:'🥣', protein:13, cal:250, carbs:36, fat:6,  fiber:9, sodium:440, calcium:55,  iron:3.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'fjSbadj9-_o', desc:'Split chickpea lentil with grated coconut, curry leaves and dried chilli — South Indian coastal style, no North Indian spice' },
  { id:2044, name:'Moong Dal Uttapam',     cat:'dal',    emoji:'🥣', protein:12, cal:220, carbs:32, fat:5,  fiber:5, sodium:340, calcium:55,  iron:2.5, vitC:8,  servingSize:'2 uttapams',  bestMeal:['breakfast'],                difficulty:'medium', prepTime:25, ytId:null,          desc:'Thick moong dal pancakes topped with onion and tomato — no rice, no fermentation, higher protein than regular uttapam' },
  { id:2126, name:'Dal Dhokli',            cat:'dal',    emoji:'🥣', protein:13, cal:320, carbs:52, fat:7,  fiber:8, sodium:420, calcium:65,  iron:3.5, vitC:6,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:40, ytId:'ro8pCoI6Xc8', desc:'Gujarati spiced toor dal with wheat flour dumplings cooked inside — one-pot comfort masterpiece unknown outside Gujarat' },
  { id:2127, name:'Amti',                  cat:'dal',    emoji:'🥣', protein:11, cal:220, carbs:32, fat:5,  fiber:7, sodium:400, calcium:55,  iron:3.0, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'oTl_DYNAP0o', desc:'Maharashtrian toor dal with kokum, jaggery and goda masala — the sweet-sour-spicy balance unique to Maharashtra' },
  { id:2128, name:'Pitla',                 cat:'dal',    emoji:'🥣', protein:12, cal:200, carbs:24, fat:7,  fiber:4, sodium:380, calcium:55,  iron:2.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:'udXqe3BixEk', desc:'Maharashtrian chickpea flour gravy — village protein dish eaten with bhakri or jowar roti, zero refined ingredients' },
  { id:2129, name:'Burani Dal',            cat:'dal',    emoji:'🥣', protein:10, cal:210, carbs:28, fat:6,  fiber:6, sodium:400, calcium:55,  iron:2.8, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'QH5vUwMqwaY', desc:'Hyderabadi dal with a lavish fried garlic tadka poured on last — a technique that makes it taste different from every other dal' },
  { id:2130, name:'Matki Usal',            cat:'dal',    emoji:'🥣', protein:14, cal:220, carbs:30, fat:5,  fiber:10, sodium:360, calcium:70, iron:4.0, vitC:8,  servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:30, ytId:'nCFxRM-N9DA', desc:'Sprouted moth beans in tangy Maharashtrian masala — on every Pune street corner, almost unknown north of the Vindhyas' },
  { id:3021, name:'Bhaja Muger Dal',       cat:'dal',    emoji:'🥣', protein:12, cal:210, carbs:30, fat:5,  fiber:7, sodium:340, calcium:50,  iron:3.0, vitC:4,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'CW5cwTA7hDg', desc:'Bengali dry-roasted moong dal with fried ginger — nutty, aromatic and completely different from boiled or tadka moong' },
  { id:3022, name:'Sindhi Dal Pakwan',     cat:'dal',    emoji:'🥣', protein:13, cal:380, carbs:58, fat:10, fiber:9, sodium:420, calcium:60,  iron:4.0, vitC:5,  servingSize:'1 plate',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:45, ytId:'rrWR0t4u5LI', desc:'Sindhi chana dal with crispy fried pakwan — Sindhi community festival dish, richer and more complex than any dal breakfast' },
  { id:3023, name:'Kulathi Dal',           cat:'dal',    emoji:'🥣', protein:15, cal:220, carbs:30, fat:3,  fiber:12, sodium:360, calcium:80, iron:7.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:45, ytId:'8OHkpjKbj4c', desc:'Horse gram — highest-protein legume in India — cooked Maharashtrian style, virtually unknown north of the Vindhyas' },
  { id:3024, name:'Goan Kokum Toor Dal',   cat:'dal',    emoji:'🥣', protein:11, cal:230, carbs:34, fat:5,  fiber:8, sodium:380, calcium:55,  iron:3.0, vitC:4,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:30, ytId:'ZOI3K0G1V_4', desc:'Toor dal with kokum and coconut — Goan technique that makes arhar taste completely different from any North Indian version' },
  { id:3025, name:'Chana Dal Lauki',       cat:'dal',    emoji:'🥣', protein:12, cal:220, carbs:32, fat:5,  fiber:9, sodium:380, calcium:60,  iron:3.0, vitC:10, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:30, ytId:'t6KJVnsqS-M', desc:'Chana dal slow-cooked with bottle gourd — the low-calorie high-protein combination that balances every macro without trying' },
  { id:3026, name:'Vathal Kuzhambu',       cat:'dal',    emoji:'🥣', protein:9,  cal:200, carbs:26, fat:8,  fiber:6, sodium:500, calcium:60,  iron:4.5, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'3NAf1UEE8E0', desc:'Tamil tangy tamarind gravy with sun-dried sundakkai — pungent, warming and completely unlike any other dal or rasam' },
  { id:3027, name:'Palakura Pappu',        cat:'dal',    emoji:'🥣', protein:12, cal:200, carbs:26, fat:5,  fiber:8, sodium:360, calcium:90,  iron:4.5, vitC:28, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:25, ytId:'bJItzde0X-U', desc:'Andhra-style spinach cooked into toor dal with tamarind and green chilli — served with rice and ghee, eaten like dal in other states' },

  // ── LEGUMES & BEANS ───────────────────────────────────── (15) ──
  { id:2018, name:'Rajma Tikki',           cat:'legumes',emoji:'🫘', protein:10, cal:200, carbs:26, fat:6,  fiber:8,  sodium:360, calcium:60,  iron:3.0, vitC:4,  servingSize:'3 tikkis',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:25, ytId:'-w6z7VBFeh0', desc:'Melt-in-mouth kidney bean patties — the rajma lover\'s street food form with mint chutney, completely different from rajma chawal' },
  { id:2022, name:'Rajma Cutlet',          cat:'legumes',emoji:'🫘', protein:11, cal:220, carbs:30, fat:6,  fiber:7,  sodium:380, calcium:65,  iron:3.0, vitC:5,  servingSize:'3 cutlets',   bestMeal:['snacks'],                  difficulty:'medium', prepTime:25, ytId:'Z29q7-t3sko', desc:'Shallow-fried kidney bean cutlets with caramelised onion — more refined than a tikki, great with tamarind chutney' },
  { id:2122, name:'Rajma Galouti Kebab',   cat:'legumes',emoji:'🫘', protein:11, cal:230, carbs:28, fat:8,  fiber:7,  sodium:380, calcium:60,  iron:3.5, vitC:4,  servingSize:'3 kebabs',    bestMeal:['snacks','dinner'],          difficulty:'hard',   prepTime:45, ytId:'VKaeC25l3lE', desc:'Lucknawi melt-in-mouth patties from finely ground rajma with raw papaya — extraordinary texture, no meat required' },
  { id:2123, name:'Kashmiri Rajma Curry',  cat:'legumes',emoji:'🫘', protein:13, cal:290, carbs:40, fat:7,  fiber:10, sodium:460, calcium:70,  iron:4.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:45, ytId:'qJGPHbW3q8A', desc:'Small Kashmiri red beans in fennel-asafoetida-dry ginger gravy — completely different from Punjabi rajma in every way' },
  { id:2027, name:'Amritsari Chhole',      cat:'legumes',emoji:'🫘', protein:14, cal:300, carbs:42, fat:8,  fiber:11, sodium:520, calcium:90,  iron:4.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:40, ytId:'_e1hHIbdBUw', desc:'Black tea-brewed dark chickpeas with authentic Punjabi spice blend — the real version with baking soda and anardana' },
  { id:2031, name:'Chhole Kulche',         cat:'legumes',emoji:'🫘', protein:14, cal:420, carbs:66, fat:10, fiber:9,  sodium:560, calcium:90,  iron:4.0, vitC:5,  servingSize:'1 plate',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:35, ytId:'BeT4A0P2NaQ', desc:'Spicy chhole with soft baked kulcha — Delhi street combination made properly at home with no tandoor needed' },
  { id:2032, name:'Kala Chana Masala',     cat:'legumes',emoji:'🫘', protein:13, cal:280, carbs:44, fat:6,  fiber:12, sodium:480, calcium:75,  iron:5.0, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:40, ytId:'gZcO8d2btZo', desc:'Black chickpeas in dry masala — higher iron than regular chhole, earthier taste and texture, the underdog legume' },
  { id:2124, name:'Chhole Palak',          cat:'legumes',emoji:'🫘', protein:13, cal:250, carbs:30, fat:8,  fiber:10, sodium:460, calcium:100, iron:5.0, vitC:20, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'_EvixoDw9dc', desc:'Iron double-win — chickpeas slow-cooked into spinach gravy with whole spices, more nutritious than palak paneer' },
  { id:2125, name:'Sukhe Kale Chhole',     cat:'legumes',emoji:'🫘', protein:12, cal:240, carbs:38, fat:5,  fiber:12, sodium:380, calcium:70,  iron:6.0, vitC:5,  servingSize:'1 bowl',      bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:15, ytId:'krPftkb32oE', desc:'Boiled black chickpeas tossed dry with cumin, amchur and raw onion — Delhi street breakfast protein bomb, zero fat' },
  { id:3028, name:'Surti Val Dal',         cat:'legumes',emoji:'🫘', protein:13, cal:260, carbs:40, fat:4,  fiber:11, sodium:380, calcium:80,  iron:3.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:45, ytId:null,          desc:'Gujarati field bean curry — val is ubiquitous in Gujarat but virtually unknown elsewhere, earthy and hearty with kokum' },
  { id:3029, name:'Chavli Rassa',          cat:'legumes',emoji:'🫘', protein:14, cal:260, carbs:36, fat:6,  fiber:10, sodium:400, calcium:60,  iron:4.5, vitC:6,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:35, ytId:'DtcJstJBnAU', desc:'Maharashtrian black-eyed pea curry with ground coconut and kanda-lasun masala — the legume Pune eats instead of rajma' },
  { id:3030, name:'Vaal Ki Dal',           cat:'legumes',emoji:'🫘', protein:12, cal:250, carbs:38, fat:4,  fiber:10, sodium:360, calcium:65,  iron:3.5, vitC:4,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:60, ytId:null,          desc:'Gujarati hyacinth bean dal with kokum and jaggery — buttery texture, takes time to peel but delivers extraordinary flavour' },
  { id:3031, name:'Hara Chana Sabzi',      cat:'legumes',emoji:'🫘', protein:13, cal:240, carbs:34, fat:5,  fiber:10, sodium:340, calcium:75,  iron:4.0, vitC:12, servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:20, ytId:'w3_ofMkwbEA', desc:'Fresh green chickpeas tempered with cumin and coriander — winter superfood with 3x vitamin C of dried chana' },
  { id:3032, name:'Dry Lobia Masala',      cat:'legumes',emoji:'🫘', protein:13, cal:230, carbs:34, fat:5,  fiber:9,  sodium:360, calcium:55,  iron:4.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:35, ytId:'aIWhqAxZkAc', desc:'Dry black-eyed peas with ginger-tomato masala — the southern staple protein that North India barely knows exists' },
  { id:3082, name:'Harbhara Amti',         cat:'legumes',emoji:'🫘', protein:12, cal:240, carbs:34, fat:6,  fiber:9,  sodium:360, calcium:70,  iron:3.5, vitC:10, servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:null,          desc:'Fresh green chickpeas in Maharashtrian amti with jaggery and tamarind — seasonal Holi dish unavailable rest of the year' },

  // ── SPROUTS ───────────────────────────────────────────── (10) ──
  { id:2054, name:'Sprouts Chaat',         cat:'sprouts',emoji:'🌱', protein:9,  cal:160, carbs:24, fat:3,  fiber:6,  sodium:280, calcium:45,  iron:2.8, vitC:15, servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:10, ytId:null,          desc:'Sprouted moong chaat with chutneys, pomegranate and black salt — zero cooking, maximum flavour and 9g protein' },
  { id:2055, name:'Sprouts Tikki',         cat:'sprouts',emoji:'🌱', protein:9,  cal:180, carbs:26, fat:4,  fiber:5,  sodium:300, calcium:40,  iron:2.5, vitC:8,  servingSize:'3 tikkis',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:20, ytId:null,          desc:'Pan-fried sprouted lentil patties with coriander-garlic chutney — crunchier and more nutritious than aloo tikki' },
  { id:2057, name:'Sprouts Pulao',         cat:'sprouts',emoji:'🌱', protein:10, cal:280, carbs:50, fat:3,  fiber:7,  sodium:360, calcium:50,  iron:3.0, vitC:8,  servingSize:'1 cup',       bestMeal:['lunch'],                   difficulty:'medium', prepTime:25, ytId:null,          desc:'Basmati cooked with mixed sprouts and whole spices — the protein-first take on everyday pulao' },
  { id:2058, name:'Sprouts Stuffed Roti',  cat:'sprouts',emoji:'🌱', protein:10, cal:280, carbs:44, fat:5,  fiber:7,  sodium:320, calcium:50,  iron:3.0, vitC:8,  servingSize:'2 rotis',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:20, ytId:null,          desc:'Whole-wheat roti stuffed with spiced sprouted moong — the high-protein flatbread almost no one talks about' },
  { id:2132, name:'Sprouts Sundal',        cat:'sprouts',emoji:'🌱', protein:10, cal:180, carbs:26, fat:4,  fiber:8,  sodium:240, calcium:50,  iron:3.0, vitC:10, servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:15, ytId:null,          desc:"South Indian stir-fried sprouts with coconut, curry leaves and mustard — temple prasad that's effortlessly healthy" },
  { id:3033, name:'Moong Sprouts Paratha', cat:'sprouts',emoji:'🌱', protein:12, cal:300, carbs:44, fat:6,  fiber:7,  sodium:320, calcium:55,  iron:3.0, vitC:10, servingSize:'2 parathas',  bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'1ksXUchqS9A', desc:'Whole wheat paratha stuffed with spiced sprouted moong — the most nutritionally complete Indian flatbread' },
  { id:3034, name:'Sprouted Moong Idli',   cat:'sprouts',emoji:'🌱', protein:12, cal:200, carbs:32, fat:2,  fiber:5,  sodium:280, calcium:50,  iron:2.5, vitC:8,  servingSize:'4 idlis',     bestMeal:['breakfast'],                difficulty:'medium', prepTime:20, ytId:'2ptpeVjWsiI', desc:'Fermentation-free idli made from sprouted moong — higher protein than rice idli, ready in 20 minutes without soaking' },
  { id:3035, name:'Kolhapuri Sprouts Rassa',cat:'sprouts',emoji:'🌱', protein:14, cal:280, carbs:36, fat:8,  fiber:10, sodium:460, calcium:80,  iron:4.5, vitC:12, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:50, ytId:null,          desc:'Fiery Kolhapuri red rassa with mixed sprouted legumes — Kolhapuri masala is one of the most complex spice blends in Maharashtra' },
  { id:3036, name:'Chana Sprouts Stir Fry',cat:'sprouts',emoji:'🌱', protein:12, cal:200, carbs:28, fat:5,  fiber:9,  sodium:300, calcium:70,  iron:4.0, vitC:10, servingSize:'1 bowl',      bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:15, ytId:null,          desc:'Dry-stir-fried sprouted kala chana with lemon, chilli and coriander — zero oil version, highest iron breakfast option' },
  { id:3037, name:'Masala Sprouted Bhel',  cat:'sprouts',emoji:'🌱', protein:10, cal:200, carbs:32, fat:4,  fiber:8,  sodium:340, calcium:45,  iron:3.0, vitC:12, servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:10, ytId:'OB7tyagqguE', desc:'Mixed sprouts with puffed rice, chutneys and pomegranate — protein-rich Mumbai bhel upgrade, no frying required' },

  // ── SOUTH INDIAN ──────────────────────────────────────── (12) ──
  { id:2097, name:'Pesarattu',             cat:'southindian',emoji:'🫓', protein:12, cal:220, carbs:32, fat:4,  fiber:6, sodium:280, calcium:50,  iron:3.0, vitC:5,  servingSize:'2 dosas',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:20, ytId:'ZOTgfPwBivA', desc:'Andhra green moong dosa — no rice, no fermentation, pure protein — the original high-protein dosa, crispy and light' },
  { id:2100, name:'Adai Dosa',             cat:'southindian',emoji:'🫓', protein:14, cal:250, carbs:36, fat:6,  fiber:6, sodium:320, calcium:60,  iron:3.0, vitC:6,  servingSize:'2 adais',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:null,          desc:'Multi-lentil thick dosa with 5 different dals — twice the protein of regular dosa, crispy outside soft inside' },
  { id:2105, name:'Kuzhi Paniyaram',       cat:'southindian',emoji:'🫓', protein:8,  cal:220, carbs:36, fat:5,  fiber:3, sodium:300, calcium:45,  iron:1.8, vitC:3,  servingSize:'6 pieces',    bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:20, ytId:'T_psJBhd4Lc', desc:'Crispy outside, soft inside fermented rice-lentil dumplings cooked in a mould — better than regular appe' },
  { id:2106, name:'Kozhukattai',           cat:'southindian',emoji:'🫓', protein:6,  cal:200, carbs:36, fat:4,  fiber:3, sodium:120, calcium:30,  iron:1.2, vitC:2,  servingSize:'4 pieces',    bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:25, ytId:null,          desc:"Tamil Nadu steamed rice flour dumplings with coconut-lentil stuffing — the underrated festival breakfast" },
  { id:2144, name:'Paruppu Urundai Kulambu',cat:'southindian',emoji:'🫓', protein:14, cal:280, carbs:36, fat:8, fiber:8, sodium:420, calcium:70, iron:4.0, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:50, ytId:null,          desc:'Tamil Nadu lentil balls simmered in tamarind-coconut curry — festive dish rarely made at home, extraordinary flavour' },
  { id:2145, name:'Thavala Adai',          cat:'southindian',emoji:'🫓', protein:13, cal:240, carbs:36, fat:5,  fiber:6, sodium:300, calcium:55,  iron:3.0, vitC:5,  servingSize:'2 adais',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:30, ytId:null,          desc:'Kerala crispy multi-grain adai with 5 lentils and rice — more protein than regular dosa, incredible crunch' },
  { id:2146, name:'Keerai Vadai',          cat:'southindian',emoji:'🫓', protein:11, cal:220, carbs:26, fat:8,  fiber:5, sodium:340, calcium:70,  iron:3.5, vitC:15, servingSize:'4 vadais',    bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:30, ytId:null,          desc:'Crispy urad dal vadas mixed with fresh spinach — green protein-rich upgrade on regular medu vada' },
  { id:3038, name:'Ven Pongal',            cat:'southindian',emoji:'🫓', protein:12, cal:320, carbs:50, fat:10, fiber:4, sodium:340, calcium:50,  iron:2.5, vitC:3,  servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:25, ytId:'2m9Bd-JQ4mU', desc:'Tamil Nadu breakfast — moong dal and rice with black pepper, cumin and cashews in ghee — deeply comforting' },
  { id:3039, name:'Vazhaipoo Vadai',       cat:'southindian',emoji:'🫓', protein:11, cal:240, carbs:28, fat:8,  fiber:8, sodium:320, calcium:70,  iron:3.5, vitC:12, servingSize:'4 vadais',    bestMeal:['snacks'],                  difficulty:'hard',   prepTime:50, ytId:'sXZNpPAKTjg', desc:'Banana flower and urad dal crispy patties — high iron, extraordinary flavour, rarely made at home due to prep' },
  { id:3040, name:'Ash Gourd Kootu',       cat:'southindian',emoji:'🫓', protein:10, cal:200, carbs:24, fat:8,  fiber:6, sodium:300, calcium:80,  iron:2.5, vitC:10, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:null,          desc:'Tamil Nadu ash gourd and chana dal stew with ground coconut — cooling, light and nutritionally complete' },
  { id:3041, name:'Avial',                 cat:'southindian',emoji:'🫓', protein:7,  cal:220, carbs:22, fat:12, fiber:7, sodium:280, calcium:80,  iron:2.0, vitC:25, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:40, ytId:'e1HRlyAUxBU', desc:'Kerala mixed vegetable stew in coconut-curd — mythologically invented by Bhima, every vegetable contributes a different texture' },
  { id:3042, name:'Kanchipuram Idli',      cat:'southindian',emoji:'🫓', protein:8,  cal:210, carbs:36, fat:5,  fiber:3, sodium:300, calcium:40,  iron:2.0, vitC:2,  servingSize:'3 idlis',     bestMeal:['breakfast'],                difficulty:'medium', prepTime:30, ytId:'4nCYRbOIQVg', desc:'Temple idli from Kanchipuram flavoured with black pepper, cumin, asafoetida and gingelly oil — unlike any regular idli' },

  // ── MILLETS & GRAINS ──────────────────────────────────── (12) ──
  { id:2067, name:'Quinoa Pulao',          cat:'millet', emoji:'🌾', protein:12, cal:320, carbs:50, fat:7,  fiber:4, sodium:380, calcium:50,  iron:2.5, vitC:8,  servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:25, ytId:null,          desc:'Protein-rich quinoa cooked with vegetables and whole spices — 50% more protein per serving than rice pulao' },
  { id:2068, name:'Quinoa Salad',          cat:'millet', emoji:'🌾', protein:11, cal:280, carbs:42, fat:8,  fiber:5, sodium:280, calcium:55,  iron:2.8, vitC:15, servingSize:'1 bowl',      bestMeal:['lunch','snacks'],           difficulty:'easy',   prepTime:20, ytId:null,          desc:'Cold quinoa with roasted veggies, chickpeas and tahini-lemon dressing — the gym meal that actually tastes good' },
  { id:2073, name:'Quinoa Khichdi',        cat:'millet', emoji:'🌾', protein:12, cal:300, carbs:48, fat:5,  fiber:6, sodium:360, calcium:55,  iron:2.8, vitC:6,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:25, ytId:'qcdMqTLUblg', desc:'Quinoa and moong dal cooked together with turmeric and ghee — same soul as khichdi, double the protein' },
  { id:2075, name:'Quinoa Upma',           cat:'millet', emoji:'🌾', protein:11, cal:280, carbs:44, fat:6,  fiber:4, sodium:340, calcium:50,  iron:2.5, vitC:8,  servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:20, ytId:null,          desc:'Quinoa cooked upma-style with mustard, curry leaves and mixed vegetables — South Indian feel, global grain' },
  { id:2136, name:'Oats Adai',             cat:'millet', emoji:'🌾', protein:13, cal:240, carbs:34, fat:5,  fiber:6, sodium:320, calcium:60,  iron:2.8, vitC:5,  servingSize:'2 adais',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:null,          desc:'Oats and mixed lentil thick crispy pancake — South Indian technique, 30% more protein than regular oats porridge' },
  { id:3043, name:'Bajra Khichdi',         cat:'millet', emoji:'🌾', protein:10, cal:300, carbs:48, fat:7,  fiber:6, sodium:360, calcium:80,  iron:4.0, vitC:3,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:30, ytId:'A8n-mnXB6Do', desc:'Rajasthani pearl millet and dal khichdi — warmer than rice khichdi, higher iron, the village winter staple of Rajasthan' },
  { id:3044, name:'Ragi Mudde',            cat:'millet', emoji:'🌾', protein:8,  cal:280, carbs:58, fat:2,  fiber:5, sodium:120, calcium:360, iron:5.0, vitC:2,  servingSize:'2 muddes',    bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:20, ytId:'9Oywa7T6FY4', desc:'Karnataka finger millet balls eaten with sambar — highest calcium of any Indian staple, the traditional Karnataka evening meal' },
  { id:3045, name:'Jowar Bhakri',          cat:'millet', emoji:'🌾', protein:7,  cal:240, carbs:48, fat:2,  fiber:5, sodium:100, calcium:50,  iron:4.0, vitC:2,  servingSize:'2 bhakris',   bestMeal:['breakfast','lunch','dinner'],difficulty:'medium', prepTime:20, ytId:'GvfQHrm64dM', desc:'Hand-patted sorghum flatbread from Maharashtra — gluten-free, earthy, the Marathwada staple eaten with thecha' },
  { id:3046, name:'Thinai Pongal',         cat:'millet', emoji:'🌾', protein:9,  cal:290, carbs:52, fat:8,  fiber:5, sodium:300, calcium:40,  iron:2.5, vitC:2,  servingSize:'1 bowl',      bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'t4EmZG-vpR8', desc:'Foxtail millet version of pongal — lower glycemic index than rice, same comfort, ancient Tamil grain getting a revival' },
  { id:3047, name:'Rajgira Paratha',       cat:'millet', emoji:'🌾', protein:9,  cal:280, carbs:40, fat:9,  fiber:5, sodium:220, calcium:160, iron:5.0, vitC:3,  servingSize:'2 parathas',  bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'xvumWbQ1FfE', desc:'Amaranth flour paratha — higher calcium than dairy, wheat-free, complete protein source available year round not just navratri' },
  { id:3048, name:'Kuttu Ki Puri',         cat:'millet', emoji:'🌾', protein:7,  cal:260, carbs:38, fat:9,  fiber:4, sodium:180, calcium:50,  iron:3.0, vitC:2,  servingSize:'3 puris',     bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:20, ytId:'da2dH58SnPQ', desc:'Buckwheat puri — gluten-free, nutty flavour, eaten only during fasting months but daily-meal worthy any time' },
  { id:3049, name:'Samak Pulao',           cat:'millet', emoji:'🌾', protein:7,  cal:280, carbs:52, fat:5,  fiber:4, sodium:280, calcium:40,  iron:1.5, vitC:5,  servingSize:'1.5 cups',    bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:20, ytId:'CIHLhX0Wvoo', desc:'Barnyard millet pulao with vegetables — fastest-cooking millet, usually fasting-only but deserves a place in everyday meals' },

  // ── GREENS & SABZI ────────────────────────────────────── (12) ──
  { id:2079, name:'Methi Thepla',          cat:'greens', emoji:'🥬', protein:8,  cal:260, carbs:38, fat:7,  fiber:5, sodium:360, calcium:100, iron:3.0, vitC:12, servingSize:'3 theplas',   bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'l-6wWsZoFpE', desc:'Thin Gujarati flatbread with fenugreek and spices — iron-rich, travels well for days, addictive with curd' },
  { id:2081, name:'Green Moong Dal',       cat:'greens', emoji:'🥬', protein:12, cal:200, carbs:28, fat:3,  fiber:7, sodium:360, calcium:55,  iron:3.0, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:'BmNtLpTTzc8', desc:'Whole green moong with ginger, turmeric and lemon — the simplest high-protein dal, always skipped in favour of arhar' },
  { id:2083, name:'Broccoli Paneer Stir Fry',cat:'greens',emoji:'🥬', protein:15, cal:240, carbs:10, fat:16, fiber:4, sodium:400, calcium:240, iron:2.5, vitC:85, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:null,          desc:'High-protein stir fry with broccoli and paneer — 85mg vitamin C plus 15g protein per bowl' },
  { id:2137, name:'Keerai Kootu',          cat:'greens', emoji:'🥬', protein:11, cal:190, carbs:24, fat:6,  fiber:7, sodium:320, calcium:130, iron:4.0, vitC:30, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'SB_7RyYHCvA', desc:'Tamil Nadu spinach and lentil stew with ground coconut — earthy, iron-dense and deeply satisfying' },
  { id:2138, name:'Sarson Ka Saag',        cat:'greens', emoji:'🥬', protein:10, cal:220, carbs:18, fat:12, fiber:7, sodium:380, calcium:180, iron:5.0, vitC:40, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:60, ytId:'-yhf5fx6LQM', desc:'Punjabi triple-green saag — mustard, spinach, bathua — slow-cooked 3 hours, the only way to eat it properly' },
  { id:2139, name:'Methi Muthia',          cat:'greens', emoji:'🥬', protein:9,  cal:210, carbs:32, fat:5,  fiber:5, sodium:280, calcium:90,  iron:3.5, vitC:15, servingSize:'8 pieces',    bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:30, ytId:null,          desc:'Gujarati steamed chickpea-wheat dumplings with fenugreek — guilt-free snack rarely seen outside Gujarat' },
  { id:3050, name:'Chaulai Ka Saag',       cat:'greens', emoji:'🥬', protein:5,  cal:120, carbs:14, fat:4,  fiber:5, sodium:280, calcium:200, iron:6.0, vitC:40, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:null,          desc:'Red amaranth leaves cooked with garlic — highest calcium-per-calorie of any Indian saag, almost no one cooks this at home' },
  { id:3051, name:'Bathua Paratha',        cat:'greens', emoji:'🥬', protein:9,  cal:270, carbs:40, fat:7,  fiber:5, sodium:300, calcium:140, iron:4.0, vitC:15, servingSize:'2 parathas',  bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'2DUht4E-ts4', desc:"Paratha stuffed with bathua saag — winter superfood with 4x iron of spinach, available December-February only" },
  { id:3052, name:'Moringa Stir Fry',      cat:'greens', emoji:'🥬', protein:6,  cal:100, carbs:10, fat:4,  fiber:4, sodium:200, calcium:200, iron:6.0, vitC:60, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:15, ytId:null,          desc:'Drumstick leaves stir-fried with lentils — most nutrient-dense green in Indian cooking, 7x vitamin C of oranges' },
  { id:3053, name:'Bharwa Shimla Mirch',   cat:'greens', emoji:'🥬', protein:14, cal:280, carbs:18, fat:16, fiber:4, sodium:420, calcium:200, iron:2.0, vitC:120,servingSize:'2 capsicums',  bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:35, ytId:'O0ITeLcmstI', desc:'Capsicum stuffed with spiced paneer — 120mg vitamin C from pepper plus 14g protein from paneer, a nutritional powerhouse' },
  { id:3054, name:'Palak Makai',           cat:'greens', emoji:'🥬', protein:8,  cal:220, carbs:26, fat:8,  fiber:5, sodium:360, calcium:120, iron:3.5, vitC:30, servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:25, ytId:'SdSR3BJ_ueU', desc:'Sweetcorn kernels in spiced spinach gravy — iron from spinach, fibre from corn, naturally sweet and kid-friendly' },
  { id:3055, name:'Hara Chana Stir Fry',   cat:'greens', emoji:'🥬', protein:12, cal:220, carbs:30, fat:4,  fiber:9, sodium:280, calcium:70,  iron:3.5, vitC:10, servingSize:'1 bowl',      bestMeal:['snacks','breakfast'],       difficulty:'easy',   prepTime:15, ytId:null,          desc:'Dry-tossed fresh green chickpeas with mustard, turmeric and coconut — seasonal winter find, unknown outside Gujarat' },

  // ── NUTS & SEEDS ──────────────────────────────────────── (10) ──
  { id:2087, name:'Peanut Chutney Dosa',   cat:'nuts',   emoji:'🥜', protein:10, cal:320, carbs:46, fat:10, fiber:4, sodium:380, calcium:50,  iron:1.8, vitC:4,  servingSize:'2 dosas',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:20, ytId:null,          desc:'Crispy rice dosa with protein-rich homemade peanut chutney — groundnuts add 5g extra protein per serving' },
  { id:2088, name:'Mixed Nut Ladoo',       cat:'nuts',   emoji:'🥜', protein:7,  cal:260, carbs:20, fat:16, fiber:3, sodium:20,  calcium:60,  iron:2.0, vitC:2,  servingSize:'3 pieces',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:20, ytId:null,          desc:'Energy-dense nut balls with dates and seeds — real food alternative to protein bars, no refined sugar involved' },
  { id:2089, name:'Sesame Peanut Chikki',  cat:'nuts',   emoji:'🥜', protein:8,  cal:200, carbs:18, fat:12, fiber:2, sodium:30,  calcium:80,  iron:2.5, vitC:1,  servingSize:'2 pieces',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:20, ytId:null,          desc:'Crunchy jaggery-bound sesame and peanut brittle — iron, calcium and protein in one bite, the original energy bar' },
  { id:2140, name:'Badam Shorba',          cat:'nuts',   emoji:'🥜', protein:8,  cal:220, carbs:10, fat:16, fiber:3, sodium:280, calcium:80,  iron:1.5, vitC:4,  servingSize:'1 bowl',      bestMeal:['snacks','dinner'],          difficulty:'medium', prepTime:30, ytId:'LeIRDi1rFp4', desc:'Mughlai almond cream soup with saffron, cardamom and rose water — fine-dining restaurant starter you can make at home' },
  { id:2141, name:'Makhane Ki Sabzi',      cat:'nuts',   emoji:'🥜', protein:9,  cal:250, carbs:18, fat:16, fiber:3, sodium:380, calcium:60,  iron:1.5, vitC:5,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:null,          desc:'Roasted lotus seeds in rich cashew-tomato gravy — unusual, delicious and lower-carb than most curries' },
  { id:3056, name:'Makhana Kheer',         cat:'nuts',   emoji:'🥜', protein:8,  cal:260, carbs:36, fat:8,  fiber:2, sodium:80,  calcium:200, iron:1.5, vitC:2,  servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:25, ytId:'0FUgp28S_Xk', desc:'Roasted lotus seeds simmered in full-fat milk with saffron — lighter than rice kheer with more protein and calcium' },
  { id:3057, name:'Peanut Chaat',          cat:'nuts',   emoji:'🥜', protein:10, cal:260, carbs:22, fat:14, fiber:5, sodium:360, calcium:50,  iron:2.5, vitC:12, servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:10, ytId:'j9wrss_nqAQ', desc:'Boiled peanuts tossed with onion, tomato, chaat masala and lemon — fastest 10g protein snack with zero cooking' },
  { id:3058, name:'Walnut Chutney',        cat:'nuts',   emoji:'🥜', protein:6,  cal:220, carbs:8,  fat:18, fiber:3, sodium:180, calcium:50,  iron:2.0, vitC:2,  servingSize:'3 tbsp',      bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:10, ytId:'xofXvdQHmhg', desc:"Kashmiri doon chetin — walnut chutney with yogurt and spices, dense omega-3 dip completely unknown outside Kashmir" },
  { id:3059, name:'Kaju Masala',           cat:'nuts',   emoji:'🥜', protein:10, cal:340, carbs:16, fat:24, fiber:3, sodium:440, calcium:40,  iron:3.0, vitC:6,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'XP41Huw-5H0', desc:'Whole cashews in onion-tomato-cashew gravy — restaurant dish almost never made at home, indulgent and protein-rich' },
  { id:3060, name:'Shenga Amti',           cat:'nuts',   emoji:'🥜', protein:12, cal:280, carbs:20, fat:16, fiber:5, sodium:380, calcium:60,  iron:3.0, vitC:6,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:25, ytId:'hHjEw3_zWnM', desc:"Maharashtrian peanut curry with tamarind and jaggery — Solapur's signature dish, unknown north of Pune" },

  // ── SNACKS & STREET FOOD ──────────────────────────────── (15) ──
  { id:3061, name:'Khandvi',               cat:'snacks', emoji:'🍢', protein:8,  cal:200, carbs:26, fat:6,  fiber:3, sodium:320, calcium:120, iron:1.5, vitC:4,  servingSize:'8 rolls',     bestMeal:['snacks'],                  difficulty:'hard',   prepTime:30, ytId:'VfEH-rmXlHQ', desc:'Gujarati rolled chickpea-yogurt snack — thin translucent layers that demand perfect technique, deeply satisfying when right' },
  { id:3062, name:'Moong Dal Vada',        cat:'snacks', emoji:'🍢', protein:10, cal:220, carbs:24, fat:8,  fiber:5, sodium:340, calcium:50,  iron:2.5, vitC:4,  servingSize:'4 vadas',     bestMeal:['snacks'],                  difficulty:'medium', prepTime:25, ytId:'KEUHhOauJDY', desc:'Crispy fried moong dal fritters — lighter than medu vada, no fermentation required, best with mint chutney' },
  { id:3063, name:'Besan Paneer Chilla',   cat:'snacks', emoji:'🍢', protein:18, cal:280, carbs:22, fat:14, fiber:4, sodium:400, calcium:200, iron:2.5, vitC:8,  servingSize:'2 chillas',   bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:20, ytId:'gnuyZJm40mQ', desc:'Chickpea flour crepes stuffed with spiced paneer — 18g protein, high satiety, better than any protein bar' },
  { id:3064, name:'Green Moong Chilla',    cat:'snacks', emoji:'🍢', protein:14, cal:240, carbs:30, fat:6,  fiber:6, sodium:320, calcium:60,  iron:3.0, vitC:8,  servingSize:'2 chillas',   bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:15, ytId:'6JXC5N9hF6k', desc:'Soaked green moong batter crepes — no fermentation, no cooking the dal, soak 4 hours then blend and cook' },
  { id:3065, name:'Vatana Poha',           cat:'snacks', emoji:'🍢', protein:8,  cal:260, carbs:46, fat:5,  fiber:5, sodium:340, calcium:45,  iron:2.5, vitC:12, servingSize:'1 bowl',      bestMeal:['breakfast'],                difficulty:'easy',   prepTime:15, ytId:'RCyfkOZDGkc', desc:'Maharashtrian poha with whole dried green peas — adds 3g more protein than regular poha with a pleasant bite' },
  { id:3066, name:'Palak Puri',            cat:'snacks', emoji:'🍢', protein:7,  cal:240, carbs:34, fat:8,  fiber:4, sodium:280, calcium:80,  iron:3.0, vitC:20, servingSize:'3 puris',     bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:20, ytId:'hAF07-eZLQo', desc:'Deep-fried spinach puris — green, iron-rich and different from regular puri in every way, especially when made thin' },
  { id:3067, name:'Baked Mathri',          cat:'snacks', emoji:'🍢', protein:6,  cal:200, carbs:28, fat:8,  fiber:2, sodium:360, calcium:40,  iron:1.5, vitC:1,  servingSize:'5 pieces',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:35, ytId:null,          desc:'Oven-baked ajwain mathri — the Rajasthani festival cracker made without deep frying, just as crunchy' },
  { id:3068, name:'Litti Chokha',          cat:'snacks', emoji:'🍢', protein:14, cal:400, carbs:60, fat:10, fiber:8, sodium:460, calcium:60,  iron:4.0, vitC:10, servingSize:'2 littis',    bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:60, ytId:'e6Tl_sAEkNU', desc:'Bihari coal-roasted whole wheat balls stuffed with sattu, served with roasted brinjal-tomato chokha — extraordinary' },
  { id:3069, name:'Thalipeeth',            cat:'snacks', emoji:'🍢', protein:10, cal:280, carbs:42, fat:7,  fiber:6, sodium:320, calcium:80,  iron:3.0, vitC:8,  servingSize:'2 thalipeeths',bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'5Bg9rts-0UQ', desc:'Maharashtrian multigrain flatbread from 6 flours — bhajni thalipeeth is never the same twice, each flour region differs' },
  { id:3070, name:'Sabudana Thalipeeth',   cat:'snacks', emoji:'🍢', protein:6,  cal:280, carbs:52, fat:6,  fiber:2, sodium:260, calcium:60,  iron:1.5, vitC:8,  servingSize:'2 thalipeeths',bestMeal:['breakfast','snacks'],       difficulty:'medium', prepTime:20, ytId:'xeUX-XqkxNQ', desc:'Sago and peanut thalipeeth — the Maharashtrian fasting flatbread that deserves to be eaten year round, crispy outside' },
  { id:3071, name:'Andhra Punugulu',       cat:'snacks', emoji:'🍢', protein:8,  cal:220, carbs:28, fat:8,  fiber:3, sodium:300, calcium:45,  iron:2.0, vitC:4,  servingSize:'6 pieces',    bestMeal:['snacks','breakfast'],       difficulty:'medium', prepTime:20, ytId:'VARsc-lEAu4', desc:'Andhra fermented batter fritters — smaller and crispier than medu vada, eaten with gongura chutney in Andhra homes' },
  { id:3072, name:'Neer Dosa',             cat:'snacks', emoji:'🍢', protein:5,  cal:160, carbs:30, fat:3,  fiber:2, sodium:200, calcium:20,  iron:1.0, vitC:2,  servingSize:'3 dosas',     bestMeal:['breakfast'],                difficulty:'medium', prepTime:20, ytId:'UGvixjl9ik4', desc:"Coastal Karnataka's paper-thin rice water dosa — no fermentation, no grinding required, ethereally light with coconut chutney" },
  { id:3073, name:'Quinoa Chilla',         cat:'snacks', emoji:'🍢', protein:14, cal:250, carbs:28, fat:8,  fiber:5, sodium:320, calcium:60,  iron:2.5, vitC:8,  servingSize:'2 chillas',   bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:15, ytId:null,          desc:'Quinoa blended with moong dal into batter for crepes — 14g protein per serving, gluten-free, gym-level nutrition' },
  { id:3074, name:'Roasted Chana Chaat',   cat:'snacks', emoji:'🍢', protein:10, cal:180, carbs:24, fat:4,  fiber:7, sodium:360, calcium:50,  iron:3.0, vitC:10, servingSize:'1 bowl',      bestMeal:['snacks'],                  difficulty:'easy',   prepTime:5,  ytId:'gTQqMirDRFU', desc:'Roasted whole chana with raw onion, tomato, lemon and spices — zero cooking, 10g protein, under 5 minutes to make' },
  { id:3075, name:'Akki Roti',             cat:'snacks', emoji:'🍢', protein:6,  cal:220, carbs:42, fat:4,  fiber:3, sodium:280, calcium:30,  iron:1.5, vitC:5,  servingSize:'2 rotis',     bestMeal:['breakfast','lunch'],        difficulty:'medium', prepTime:25, ytId:'O0190fgPx4o', desc:"Karnataka's rice flour flatbread pressed by hand — gluten-free, slightly crispy outside, soft inside, eaten with chutney" },
  { id:3083, name:'Rajgira Ladoo',         cat:'snacks', emoji:'🍢', protein:7,  cal:220, carbs:24, fat:10, fiber:4, sodium:30,  calcium:160, iron:5.0, vitC:2,  servingSize:'3 pieces',    bestMeal:['snacks'],                  difficulty:'medium', prepTime:20, ytId:null,          desc:'Amaranth seed ladoos with jaggery and ghee — iron-rich navratri sweet eaten year-round by athletes for quick energy' },
  { id:3084, name:'Moong Dal Cheela Roll', cat:'snacks', emoji:'🍢', protein:16, cal:280, carbs:28, fat:10, fiber:6, sodium:360, calcium:70,  iron:3.0, vitC:10, servingSize:'2 rolls',     bestMeal:['breakfast','snacks'],       difficulty:'easy',   prepTime:20, ytId:null,          desc:'Thin moong dal cheela rolled with mint chutney and crunchy onion — a portable protein roll that beats any wrap' },

  // ── RICE DISHES ───────────────────────────────────────── (10) ──
  { id:2092, name:'Bisi Bele Bath',        cat:'rice',   emoji:'🍚', protein:12, cal:380, carbs:62, fat:8,  fiber:8, sodium:480, calcium:70,  iron:3.5, vitC:8,  servingSize:'1 bowl',      bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:45, ytId:'Gm8yj88dlFk', desc:'Karnataka one-pot rice, dal and vegetable dish with custom bisi bele spice mix — each cook has a secret recipe' },
  { id:2094, name:'Tamarind Rice',         cat:'rice',   emoji:'🍚', protein:8,  cal:320, carbs:56, fat:8,  fiber:3, sodium:400, calcium:45,  iron:2.0, vitC:4,  servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:20, ytId:'t5w-Qb4JRUk', desc:'Andhra puliyodarai — tangy tamarind rice with peanuts, temple style not the shortcut version' },
  { id:2142, name:'Dal Baati Churma',      cat:'rice',   emoji:'🍚', protein:14, cal:520, carbs:76, fat:14, fiber:10, sodium:440, calcium:65, iron:4.5, vitC:5,  servingSize:'2 baatis',    bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:60, ytId:'mZ4xTelTAGk', desc:"Rajasthani baked wheat balls with panchmel dal and ghee — a protein feast that is a complete meal in itself" },
  { id:2143, name:'Vagharela Bhaat',       cat:'rice',   emoji:'🍚', protein:9,  cal:300, carbs:52, fat:6,  fiber:3, sodium:320, calcium:40,  iron:1.5, vitC:6,  servingSize:'1.5 cups',    bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:15, ytId:null,          desc:'Gujarati tempered leftover rice with mustard, curry leaves, peanuts and lemon — humble, addictive and zero waste' },
  { id:3076, name:'Vangi Bath',            cat:'rice',   emoji:'🍚', protein:9,  cal:320, carbs:54, fat:8,  fiber:5, sodium:400, calcium:45,  iron:2.5, vitC:6,  servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'medium', prepTime:30, ytId:'KlaJRKZDo04', desc:'Karnataka eggplant rice with custom vangi bath powder — the spice blend makes it unlike any other brinjal preparation' },
  { id:3077, name:'Chitranna',             cat:'rice',   emoji:'🍚', protein:8,  cal:300, carbs:52, fat:8,  fiber:3, sodium:360, calcium:40,  iron:2.0, vitC:8,  servingSize:'1.5 cups',    bestMeal:['breakfast','lunch'],        difficulty:'easy',   prepTime:15, ytId:'XpJdJmv0Ylk', desc:'South Indian lemon rice with peanuts and curry leaves — the temple offering that is a complete meal when made right' },
  { id:3078, name:'Thayir Sadam',          cat:'rice',   emoji:'🍚', protein:9,  cal:280, carbs:44, fat:6,  fiber:2, sodium:280, calcium:200, iron:1.0, vitC:4,  servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:10, ytId:'VFpzansM-XM', desc:'Tamil curd rice with pomegranate, grated ginger and tempered curry leaves — the most calming meal in Indian cooking' },
  { id:3079, name:'Raw Jackfruit Biryani', cat:'rice',   emoji:'🍚', protein:8,  cal:360, carbs:60, fat:8,  fiber:7, sodium:440, calcium:50,  iron:2.5, vitC:10, servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'hard',   prepTime:60, ytId:'3JNsokJwSQA', desc:'Tender green jackfruit slow-cooked in dum biryani style — meaty texture, high fibre, the best vegetarian biryani' },
  { id:3080, name:'Methi Pulao',           cat:'rice',   emoji:'🍚', protein:9,  cal:310, carbs:52, fat:6,  fiber:5, sodium:360, calcium:90,  iron:3.5, vitC:8,  servingSize:'1.5 cups',    bestMeal:['lunch','dinner'],           difficulty:'easy',   prepTime:20, ytId:'pztEqj_w6nc', desc:'Fenugreek leaves cooked into pulao — slightly bitter, aromatic, high iron and the most underrated rice dish' },
  { id:3081, name:'Kothamalli Sadam',      cat:'rice',   emoji:'🍚', protein:7,  cal:290, carbs:50, fat:6,  fiber:3, sodium:340, calcium:45,  iron:2.0, vitC:10, servingSize:'1.5 cups',    bestMeal:['lunch'],                    difficulty:'easy',   prepTime:15, ytId:'fkxj0Qg0mG4', desc:'South Indian coriander rice — the underrated cousin of lemon rice, brighter and more aromatic as a lunchbox staple' },

];

// ── RECIPE UTILITIES ──────────────────────────────────────────

function getRecipeCatLabel(catId) {
  const cat = RECIPE_CATS.find(c => c.id === catId);
  return cat ? cat.label : catId;
}

function getMealLabel(meal) {
  const map = { breakfast:'Breakfast', lunch:'Lunch', snacks:'Snacks', dinner:'Dinner' };
  return map[meal] || meal;
}

function loadTriedRecipes() {
  if (!window.ACTIVE_PROFILE) return {};
  return JSON.parse(localStorage.getItem(`ft_recipes_tried_${window.ACTIVE_PROFILE.id}`) || '{}');
}
function saveTriedRecipes(data) {
  if (!window.ACTIVE_PROFILE) return;
  localStorage.setItem(`ft_recipes_tried_${window.ACTIVE_PROFILE.id}`, JSON.stringify(data));
}

function markRecipeTried(recipeId, meal) {
  const tried = loadTriedRecipes();
  if (!tried[recipeId]) tried[recipeId] = { count:0, lastTried:0, meals:[] };
  tried[recipeId].count += 1;
  tried[recipeId].lastTried = Date.now();
  if (meal && !tried[recipeId].meals.includes(meal)) tried[recipeId].meals.push(meal);
  saveTriedRecipes(tried);
}

// ── RECOMMENDATION ALGORITHM ──────────────────────────────────
function scoreRecipe(recipe, triedData, preferredMeal) {
  let score = 1000;
  if (triedData) {
    const daysSince = (Date.now() - triedData.lastTried) / 86400000;
    const count = triedData.count || 0;
    score -= count * 80;
    score += Math.min(daysSince * 15, 300);
  }
  if (preferredMeal && recipe.bestMeal.includes(preferredMeal)) score += 200;
  return score;
}

function getRecommendedRecipes(opts = {}) {
  const { cat='all', meal=null, limit=20, minProtein=0 } = opts;
  const tried = loadTriedRecipes();
  let pool = RECIPES.filter(r => {
    if (cat !== 'all' && r.cat !== cat) return false;
    if (r.protein < minProtein) return false;
    return true;
  });
  pool.sort((a, b) => scoreRecipe(b, tried[b.id], meal) - scoreRecipe(a, tried[a.id], meal));
  return pool.slice(0, limit);
}

// getScoredRecipes — used by app.js renderRecipeGrid
// sort: 'recommended' | 'protein' | 'quick' | 'untried'
function getScoredRecipes(cat, sort, query, meal) {
  const tried = loadTriedRecipes();
  let pool = RECIPES.filter(r => {
    if (cat !== 'all' && r.cat !== cat) return false;
    if (query) {
      const q = query.toLowerCase();
      if (!r.name.toLowerCase().includes(q) && !r.desc.toLowerCase().includes(q)) return false;
    }
    return true;
  });

  if (sort === 'protein') {
    pool.sort((a, b) => b.protein - a.protein);
  } else if (sort === 'quick') {
    pool.sort((a, b) => a.prepTime - b.prepTime);
  } else if (sort === 'untried') {
    pool = pool.filter(r => !tried[r.id]);
    pool.sort((a, b) => scoreRecipe(b, tried[b.id], meal) - scoreRecipe(a, tried[a.id], meal));
  } else {
    // recommended (default)
    pool.sort((a, b) => scoreRecipe(b, tried[b.id], meal) - scoreRecipe(a, tried[a.id], meal));
  }
  return pool;
}

// getTopSuggestion — top un-tried recommendation for banner
function getTopSuggestion(cat, meal) {
  const tried = loadTriedRecipes();
  let pool = RECIPES.filter(r => {
    if (cat !== 'all' && r.cat !== cat) return false;
    return !tried[r.id];
  });
  if (!pool.length) return null;
  pool.sort((a, b) => scoreRecipe(b, tried[b.id], meal) - scoreRecipe(a, tried[a.id], meal));
  return pool[0];
}
